In [1]:
# začínáme známým kouzlem
%matplotlib inline

In [26]:
tabulka = """2015-Nov-04 17:45     04 00 48.64 +45 31 34.2  11.11  13.85 1.78508927457978 -32.0541532 145.1043 /L  12.3152
 2015-Nov-04 17:46     04 00 48.44 +45 31 34.2  11.11  13.85 1.78507641770777 -32.0534842 145.1051 /L  12.3150
 2015-Nov-04 17:47     04 00 48.25 +45 31 34.3  11.11  13.85 1.78506356110407 -32.0528153 145.1059 /L  12.3148
 2015-Nov-04 17:48     04 00 48.06 +45 31 34.3  11.11  13.85 1.78505070476870 -32.0521463 145.1067 /L  12.3146
 2015-Nov-04 17:49     04 00 47.87 +45 31 34.4  11.11  13.85 1.78503784870167 -32.0514773 145.1075 /L  12.3143
 2015-Nov-04 17:50     04 00 47.68 +45 31 34.4  11.11  13.85 1.78502499290297 -32.0508083 145.1084 /L  12.3141
 2015-Nov-04 17:51     04 00 47.49 +45 31 34.5  11.11  13.85 1.78501213737261 -32.0501393 145.1092 /L  12.3139
 2015-Nov-04 17:52     04 00 47.30 +45 31 34.5  11.11  13.85 1.78499928211061 -32.0494703 145.1100 /L  12.3137
 2015-Nov-04 17:53     04 00 47.11 +45 31 34.6  11.11  13.85 1.78498642711696 -32.0488012 145.1108 /L  12.3135
 2015-Nov-04 17:54     04 00 46.92 +45 31 34.7  11.11  13.85 1.78497357239168 -32.0481322 145.1116 /L  12.3132
 2015-Nov-04 17:55     04 00 46.73 +45 31 34.7  11.11  13.85 1.78496071793477 -32.0474631 145.1124 /L  12.3130
 2015-Nov-04 17:56     04 00 46.53 +45 31 34.8  11.11  13.85 1.78494786374623 -32.0467940 145.1132 /L  12.3128
 2015-Nov-04 17:57     04 00 46.34 +45 31 34.8  11.11  13.85 1.78493500982605 -32.0461249 145.1140 /L  12.3126
 2015-Nov-04 17:58     04 00 46.15 +45 31 34.9  11.11  13.85 1.78492215617428 -32.0454558 145.1148 /L  12.3124
 2015-Nov-04 17:59     04 00 45.96 +45 31 34.9  11.11  13.85 1.78490930279089 -32.0447867 145.1156 /L  12.3121
 2015-Nov-04 18:00     04 00 45.77 +45 31 35.0  11.11  13.85 1.78489644967590 -32.0441175 145.1164 /L  12.3119"""

In [29]:
radky = tabulka.split("\n")

In [38]:
def parse(radek):
    zaznam = {}
    time = radek.split()[1]
    rs = radek.split()
    RA = 15 * (int(rs[2]) + int(rs[3])/60 + float(rs[4])/60/60)
    DE = int(rs[5]) + int(rs[6])/60 + float(rs[7])/60/60
    zaznam[time] = (RA, DE)
    return zaznam

In [40]:
for radek in radky:
    print(parse(radek))

{'17:45': (60.20266666666666, 45.52616666666667)}
{'17:46': (60.20183333333334, 45.52616666666667)}
{'17:47': (60.20104166666666, 45.52619444444444)}
{'17:48': (60.20025, 45.52619444444444)}
{'17:49': (60.19945833333334, 45.52622222222222)}
{'17:50': (60.19866666666666, 45.52622222222222)}
{'17:51': (60.197875, 45.52625)}
{'17:52': (60.19708333333334, 45.52625)}
{'17:53': (60.19629166666667, 45.52627777777778)}
{'17:54': (60.1955, 45.52630555555555)}
{'17:55': (60.19470833333334, 45.52630555555555)}
{'17:56': (60.193875, 45.52633333333333)}
{'17:57': (60.19308333333334, 45.52633333333333)}
{'17:58': (60.19229166666666, 45.52636111111111)}
{'17:59': (60.191500000000005, 45.52636111111111)}
{'18:00': (60.190708333333326, 45.52638888888889)}